In [9]:
class Employee:
    # Create a data member to count the number of Employees
    count = 0
    
    # Create a constructor to initialize name, family, salary, department
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.count += 1
    
    # Create a function to average salary
    def average_salary(self):
        return self.salary / Employee.count

# Create a Fulltime Employee class and it should inherit the properties of Employee class
class FulltimeEmployee(Employee):
    pass

# Create the instances of Fulltime Employee class and Employee class 
e1 = Employee("Sai Kishore", "Jinks", 25000, "IT")
e2 = Employee("Varun Kumar", "Jinks", 30000, "IT")
e3 = FulltimeEmployee("Sai Sasank", "Jinks", 18000, "IT")

# Call their member functions
print(e1.average_salary())
print(e2.average_salary())
print(e3.average_salary())

8333.333333333334
10000.0
6000.0


In [10]:
import numpy as np

# Generate a random vector of size 20 with float numbers between 1 and 20
random_vector = np.random.uniform(1, 20, 20)


# Reshape the array to 4 by 5
reshaped_array = random_vector.reshape(4, 5)
print(" array after reshaping to (4,5) \n")
print(reshaped_array)

# Find the index of the maximum value in each row
max_values = np.argmax(reshaped_array, axis=1)
print("\n")
# Replace the maximum value in each row with 0
reshaped_array[np.arange(reshaped_array.shape[0]), max_values] = 0
print(" replacing the maximum value in each row with 0  \n")
print(reshaped_array)

 array after reshaping to (4,5) 

[[17.28847989 15.45151858 14.27121082 13.29881923 18.91028431]
 [15.72009924  7.82201761 18.20295097 19.69202752  9.39765105]
 [15.37598663 11.08865326  6.64442507 12.16503895  8.90206331]
 [14.32915987 13.60937465 13.60256727 13.11413613  6.98207399]]


 replacing the maximum value in each row with 0  

[[17.28847989 15.45151858 14.27121082 13.29881923  0.        ]
 [15.72009924  7.82201761 18.20295097  0.          9.39765105]
 [ 0.         11.08865326  6.64442507 12.16503895  8.90206331]
 [ 0.         13.60937465 13.60256727 13.11413613  6.98207399]]
